"""add login_token

Revision ID: 9464721af713
Revises: d5656439d8df
Create Date: 2026-06-28 10:51:26.500538
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '9464721af713'
down_revision: str | None = 'd5656439d8df'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_token',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_token_email'), 'login_token', ['email'], unique=False)
    op.create_index(op.f('ix_login_token_token_hash'), 'login_token', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_login_token_token_hash'), table_name='login_token')
    op.drop_index(op.f('ix_login_token_email'), table_name='login_token')
    op.drop_table('login_token')
    # ### end Alembic commands ###
