"""add join_code and decided_at

Revision ID: c68ab4705fc6
Revises: 9464721af713
Create Date: 2026-06-28 11:51:41.009956
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'c68ab4705fc6'
down_revision: str | None = '9464721af713'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('join_code', sa.String(length=12), nullable=False))
    op.create_index(op.f('ix_course_join_code'), 'course', ['join_code'], unique=True)
    op.add_column('enrollment', sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enrollment', 'decided_at')
    op.drop_index(op.f('ix_course_join_code'), table_name='course')
    op.drop_column('course', 'join_code')
    # ### end Alembic commands ###
